# Generated by Django 5.1.4 on 2024-12-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('COUNTRY', 'Country'), ('PROVINCE', 'Province/State'), ('DISTRICT', 'District/County'), ('REGION', 'Region/Zone'), ('MUNICIPALITY', 'Municipality'), ('CITY', 'City/Town/Village'), ('SUBURB', 'Suburb/Neighbourhood'), ('FARM', 'Farm/Plot'), ('STREET', 'Street/Lane/Avenue'), ('BUILDING', 'Building/Complex'), ('ROOM', 'Room/Office/Flat'), ('CONSTITUENCY', 'Constituency/Ward'), ('WARD', 'Ward'), ('CANTON', 'Canton'), ('ISLAND', 'Island/Archipelago/Atoll'), ('AUTONOMOUS_REGION', 'Autonomous Region'), ('SAR', 'Special Administrative Region')], max_length=100)),
                ('name', models.CharField(max_length=256)),
                ('name_year_start', models.IntegerField(blank=True, null=True)),
                ('name_year_end', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_parent', to='location.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
