# Generated by Django 5.1.4 on 2024-12-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name_abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
