# Generated by Django 5.1.4 on 2024-12-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_name_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='related_present_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to_present_location', to='location.location'),
        ),
    ]
