# Generated by Django 5.1.4 on 2024-12-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_related_present_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='related_present_location',
        ),
    ]
