# Generated by Django 5.1.4 on 2024-12-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('second_name', models.CharField(blank=True, max_length=64, null=True)),
                ('known_as', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1, null=True)),
                ('vitality', models.CharField(blank=True, choices=[('A', 'Alive'), ('D', 'Deceased'), ('U', 'Unknown')], max_length=1, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('birth_circa', models.BooleanField(default=False, help_text='Is the birth date an approximate?')),
                ('birth_date_range_start', models.DateField(blank=True, help_text='Start of birth date range (if known).', null=True)),
                ('birth_date_range_end', models.DateField(blank=True, help_text='End of birth date range (if known).', null=True)),
                ('baptism_year', models.IntegerField(blank=True, null=True)),
                ('baptism_month', models.IntegerField(blank=True, null=True)),
                ('baptism_day', models.IntegerField(blank=True, null=True)),
                ('baptism_circa', models.BooleanField(default=False, help_text='Is the baptism date an approximate?')),
                ('baptism_date_range_start', models.DateField(blank=True, help_text='Start of baptism date range (if known).', null=True)),
                ('baptism_date_range_end', models.DateField(blank=True, help_text='End of baptism date range (if known).', null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('death_month', models.IntegerField(blank=True, null=True)),
                ('death_day', models.IntegerField(blank=True, null=True)),
                ('death_circa', models.BooleanField(default=False, help_text='Is the death date an approximate?')),
                ('death_date_range_start', models.DateField(blank=True, help_text='Start of death date range (if known).', null=True)),
                ('death_date_range_end', models.DateField(blank=True, help_text='End of death date range (if known).', null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_by_father', to='person.profile')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_by_mother', to='person.profile')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
