# Generated by Django 5.1.4 on 2024-12-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_year', models.IntegerField(blank=True, null=True)),
                ('marriage_month', models.IntegerField(blank=True, null=True)),
                ('marriage_day', models.IntegerField(blank=True, null=True)),
                ('marriage_circa', models.BooleanField(default=False, help_text='Is the marriage date an approximate?')),
                ('marriage_date_range_start', models.DateField(blank=True, help_text='Start of marriage date range (if known).', null=True)),
                ('marriage_date_range_end', models.DateField(blank=True, help_text='End of marriage date range (if known).', null=True)),
                ('marriage_status', models.CharField(choices=[('M', 'Married'), ('D', 'Divorced'), ('S', 'Separated'), ('U', 'Unknown')], default='M', max_length=64)),
                ('divorce_year', models.IntegerField(blank=True, null=True)),
                ('divorce_month', models.IntegerField(blank=True, null=True)),
                ('divorce_day', models.IntegerField(blank=True, null=True)),
                ('divorce_circa', models.BooleanField(default=False, help_text='Is the divorce date an approximate?')),
                ('divorce_date_range_start', models.DateField(blank=True, help_text='Start of divorce date range (if known).', null=True)),
                ('divorce_date_range_end', models.DateField(blank=True, help_text='End of divorce date range (if known).', null=True)),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husbands', to='person.profile')),
                ('wife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wives', to='person.profile')),
            ],
            options={
                'verbose_name_plural': 'Marriages',
            },
        ),
    ]
