# Generated by Django 5.1.4 on 2024-12-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_related_present_location'),
        ('person', '0002_marriage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='baptism_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baptism_location', to='location.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_location', to='location.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='death_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_location', to='location.location'),
        ),
    ]
