# Generated by Django 5.1.4 on 2024-12-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_profile_baptism_location_profile_birth_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='familysearch_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
