# Generated by Django 5.1.4 on 2024-12-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_related_present_location'),
        ('person', '0004_profile_familysearch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='marriage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_of_marriage', to='location.location'),
        ),
    ]
