# Generated by Django 5.1.4 on 2024-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_marriage_marriage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(db_index=True, editable=False, max_length=6, unique=True),
        ),
    ]
