# Generated by Django 5.1.4 on 2025-01-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='baptism_circa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_circa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='death_circa',
        ),
        migrations.AddField(
            model_name='profile',
            name='baptism_date_type',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('BEFORE', 'Before'), ('AFTER', 'After'), ('CIRCA', 'Circa'), ('BETWEEN', 'Between'), ('UNKNOWN', 'Unknown')], default='EXACT', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date_type',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('BEFORE', 'Before'), ('AFTER', 'After'), ('CIRCA', 'Circa'), ('BETWEEN', 'Between'), ('UNKNOWN', 'Unknown')], default='EXACT', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='death_date_type',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('BEFORE', 'Before'), ('AFTER', 'After'), ('CIRCA', 'Circa'), ('BETWEEN', 'Between'), ('UNKNOWN', 'Unknown')], default='EXACT', max_length=16),
        ),
    ]
