# Generated by Django 5.1.4 on 2025-01-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_related_present_location'),
        ('person', '0009_remove_profile_baptism_circa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='burial_date_range_end',
            field=models.DateField(blank=True, help_text='End of burial date range (if known).', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='burial_date_range_start',
            field=models.DateField(blank=True, help_text='Start of burial date range (if known).', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='burial_date_type',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('BEFORE', 'Before'), ('AFTER', 'After'), ('CIRCA', 'Circa'), ('BETWEEN', 'Between'), ('UNKNOWN', 'Unknown')], default='EXACT', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='burial_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='burial_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burial_location', to='location.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='burial_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='burial_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
