# Generated by Django 5.1.4 on 2025-01-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_remove_marriage_divorce_circa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='person.profile'),
        ),
    ]
